/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as DashboardIndexRouteImport } from './../routes/dashboard/index'
import { Route as DeckIdRouteImport } from './../routes/deck.$id'
import { Route as DashboardIdRouteImport } from './../routes/dashboard/$id'
import { Route as AuthGoogleCallbackRouteImport } from './../routes/auth.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckIdRoute = DeckIdRouteImport.update({
  id: '/deck/$id',
  path: '/deck/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdRoute = DashboardIdRouteImport.update({
  id: '/dashboard/$id',
  path: '/dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/deck/$id': typeof DeckIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/deck/$id': typeof DeckIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/deck/$id': typeof DeckIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/$id'
    | '/deck/$id'
    | '/dashboard'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/$id'
    | '/deck/$id'
    | '/dashboard'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/dashboard/$id'
    | '/deck/$id'
    | '/dashboard/'
    | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIdRoute: typeof DashboardIdRoute
  DeckIdRoute: typeof DeckIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$id': {
      id: '/deck/$id'
      path: '/deck/$id'
      fullPath: '/deck/$id'
      preLoaderRoute: typeof DeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIdRoute: DashboardIdRoute,
  DeckIdRoute: DeckIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
